[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-util = { version = "0.6", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3.17"
